import { addStyledHeaderRow, autoSizeColumns } from './sheetUtils.js'

const WORKBOOK_TEMPLATE_VERSION = '1.5'

export function buildInstructionsSheet(workbook, config, derived) {
  const ws = workbook.addWorksheet('Instructions')

  addStyledHeaderRow(ws, ['Topic', 'Details'])

  const templateType = config.workbookOptions?.templateType || 'simple'

  const rows = [
    ['Workbook purpose', 'This workbook was generated by AthleteOS as an editable tournament planning draft.'],
    ['Workbook template version', WORKBOOK_TEMPLATE_VERSION],
    ['Workbook template type', templateType],
    ['How to use', 'Fill in missing values, update rows as needed, then import the workbook back into AthleteOS.'],
    ['Tournament metadata', 'The Tournament tab includes template_version and template_type fields used for workbook compatibility validation.'],
    ['Do not rename tabs', 'Tab names should remain unchanged for import compatibility.'],
    ['Do not rename headers', 'Column headers should remain unchanged.'],
    ['Division names', 'Division names must match exactly across Divisions, Pools, Teams, and Rosters tabs.'],
    ['Pool names', 'Pool names must match exactly within the same division.'],
    ['Team names', 'Team names must match exactly between Teams and Rosters tabs.'],
    ['Generated divisions', `${derived.divisions.length}`],
    ['Generated fields', `${derived.fields.length}`],
    ['Generated tournament days', `${derived.tournamentDays.length}`],
    ['Include Rosters tab', config.workbookOptions.includeRosters ? 'Yes' : 'No'],
    ['Include ScheduleDraft tab', config.workbookOptions.includeScheduleDraft ? 'Yes' : 'No'],
    ['Advanced templates', 'Advanced workbook sheets such as explicit bracket configuration may be added in future workbook template upgrades.'],
    ['Example rows', 'Rows with example_row = TRUE are sample rows for guidance only and are ignored during import.'],
    ['Schedules sheet', 'The Schedules sheet exports editable match schedule rows for existing matches when available.'],
    ['Schedule editing', 'Edit scheduled_date, start_time, and field_name to adjust match scheduling. Do not change match_id or match_code for existing matches.'],
    ['Unscheduled matches', 'Leave scheduled_date, start_time, and field_name blank together if a match should remain unscheduled.'],
  ]

  rows.forEach(row => ws.addRow(row))
  autoSizeColumns(ws, 18, 60)
}