import { addStyledHeaderRow, autoSizeColumns } from './sheetUtils'

export function buildInstructionsSheet(workbook, config, derived) {
  const ws = workbook.addWorksheet('Instructions')

  addStyledHeaderRow(ws, ['Topic', 'Details'])

  const rows = [
    ['Workbook purpose', 'This workbook was generated by AthleteOS as an editable tournament planning draft.'],
    ['How to use', 'Fill in missing values, update rows as needed, then import the workbook back into AthleteOS.'],
    ['Do not rename tabs', 'Tab names should remain unchanged for import compatibility.'],
    ['Do not rename headers', 'Column headers should remain unchanged.'],
    ['Division names', 'Division names must match exactly across Divisions, Pools, Teams, and Rosters tabs.'],
    ['Pool names', 'Pool names must match exactly within the same division.'],
    ['Team names', 'Team names must match exactly between Teams and Rosters tabs.'],
    ['Generated divisions', `${derived.divisions.length}`],
    ['Generated fields', `${derived.fields.length}`],
    ['Generated tournament days', `${derived.tournamentDays.length}`],
    ['Include Rosters tab', config.workbookOptions.includeRosters ? 'Yes' : 'No'],
    ['Include ScheduleDraft tab', config.workbookOptions.includeScheduleDraft ? 'Yes' : 'No'],
    ['Schedule draft level', config.workbookOptions.scheduleDraftLevel],
  ]

  rows.forEach(row => ws.addRow(row))
  autoSizeColumns(ws, 18, 60)
}