import { useState } from 'react'
import { X, Upload, FileSpreadsheet, AlertTriangle, CheckCircle2 } from 'lucide-react'
import { processWorkbookUpload } from './processWorkbookUpload'

export function UploadWorkbookModal({ isOpen, onClose, onValidated }) {
  const [fileName, setFileName] = useState('')
  const [loading, setLoading] = useState(false)
  const [result, setResult] = useState(null)
  const [fatalError, setFatalError] = useState(null)

  if (!isOpen) return null

  async function handleFileChange(file) {
    if (!file) return

    setFileName(file.name)
    setLoading(true)
    setFatalError(null)
    setResult(null)

    try {
      const uploadResult = await processWorkbookUpload(file)
      setResult(uploadResult)
    } catch (err) {
      setFatalError(err.message || 'Failed to process workbook.')
    } finally {
      setLoading(false)
    }
  }

  function handleUseWorkbook() {
    if (!result?.validation?.valid) return
    onValidated?.(result)
    onClose?.()
  }

  const validation = result?.validation
  const errors = validation?.errors ?? []
  const warnings = validation?.warnings ?? []

  return (
    <div
      style={{
        position: 'fixed',
        inset: 0,
        zIndex: 100,
        background: 'rgba(0,0,0,0.55)',
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        padding: 20,
      }}
    >
      <div
        style={{
          width: '100%',
          maxWidth: 860,
          maxHeight: '90vh',
          overflow: 'auto',
          background: 'var(--bg-surface)',
          border: '1px solid var(--border)',
          borderRadius: 18,
          boxShadow: '0 24px 80px rgba(0,0,0,0.35)',
        }}
      >
        <div
          style={{
            padding: '18px 20px',
            borderBottom: '1px solid var(--border)',
            display: 'flex',
            alignItems: 'center',
            justifyContent: 'space-between',
            gap: 12,
          }}
        >
          <div style={{ display: 'flex', alignItems: 'center', gap: 10 }}>
            <div
              style={{
                width: 36,
                height: 36,
                borderRadius: 12,
                display: 'grid',
                placeItems: 'center',
                background: 'rgba(59,130,246,0.10)',
                color: '#3b82f6',
              }}
            >
              <FileSpreadsheet size={18} />
            </div>
            <div>
              <h2 style={{ margin: 0, fontSize: 18, fontWeight: 800, color: 'var(--text-primary)' }}>
                Upload Tournament Workbook
              </h2>
              <p style={{ margin: '4px 0 0', fontSize: 13, color: 'var(--text-muted)' }}>
                Upload a workbook to validate divisions, teams, pools, rosters, fields, and tournament days.
              </p>
            </div>
          </div>

          <button
            onClick={onClose}
            style={{
              border: '1px solid var(--border)',
              background: 'transparent',
              color: 'var(--text-muted)',
              borderRadius: 10,
              padding: 8,
              cursor: 'pointer',
            }}
          >
            <X size={16} />
          </button>
        </div>

        <div style={{ padding: 20 }} className="space-y-5">
          <div
            style={{
              border: '1px dashed var(--border)',
              borderRadius: 16,
              padding: 20,
              background: 'var(--bg-base)',
            }}
          >
            <label
              style={{
                display: 'flex',
                flexDirection: 'column',
                alignItems: 'center',
                gap: 10,
                cursor: 'pointer',
                textAlign: 'center',
              }}
            >
              <div
                style={{
                  width: 44,
                  height: 44,
                  borderRadius: 14,
                  display: 'grid',
                  placeItems: 'center',
                  background: 'rgba(59,130,246,0.10)',
                  color: '#3b82f6',
                }}
              >
                <Upload size={18} />
              </div>

              <div>
                <div style={{ fontSize: 14, fontWeight: 700, color: 'var(--text-primary)' }}>
                  Choose workbook file
                </div>
                <div style={{ fontSize: 13, color: 'var(--text-muted)', marginTop: 4 }}>
                  Upload an .xlsx workbook generated by AthleteOS or filled using the workbook template.
                </div>
              </div>

              <input
                type="file"
                accept=".xlsx"
                style={{ display: 'none' }}
                onChange={e => handleFileChange(e.target.files?.[0])}
              />

              <div style={secondaryButtonStyle()}>
                <Upload size={15} />
                Select file
              </div>
            </label>

            {fileName && (
              <p style={{ margin: '12px 0 0', fontSize: 12, color: 'var(--text-muted)' }}>
                Selected: {fileName}
              </p>
            )}
          </div>

          {loading && (
            <div
              style={{
                padding: 14,
                borderRadius: 12,
                border: '1px solid var(--border)',
                background: 'var(--bg-base)',
                color: 'var(--text-secondary)',
                fontSize: 14,
              }}
            >
              Processing workbook...
            </div>
          )}

          {fatalError && (
            <div
              style={{
                padding: 14,
                borderRadius: 12,
                border: '1px solid rgba(239,68,68,0.18)',
                background: 'rgba(239,68,68,0.08)',
                color: '#dc2626',
                fontSize: 14,
              }}
            >
              {fatalError}
            </div>
          )}

          {validation && (
            <>
              <div className="grid grid-cols-3 gap-3">
                <SummaryCard
                  label="Workbook status"
                  value={validation.valid ? 'Valid' : 'Needs fixes'}
                  tone={validation.valid ? 'green' : 'red'}
                />
                <SummaryCard
                  label="Errors"
                  value={String(errors.length)}
                  tone={errors.length > 0 ? 'red' : 'neutral'}
                />
                <SummaryCard
                  label="Warnings"
                  value={String(warnings.length)}
                  tone={warnings.length > 0 ? 'amber' : 'neutral'}
                />
              </div>

              {errors.length === 0 && warnings.length === 0 && (
                <div
                  style={{
                    padding: 14,
                    borderRadius: 12,
                    border: '1px solid rgba(34,197,94,0.18)',
                    background: 'rgba(34,197,94,0.08)',
                    color: '#15803d',
                    fontSize: 14,
                    display: 'flex',
                    alignItems: 'center',
                    gap: 8,
                  }}
                >
                  <CheckCircle2 size={16} />
                  Workbook validation passed with no errors or warnings.
                </div>
              )}

              {errors.length > 0 && (
                <IssueList title="Errors" issues={errors} tone="red" />
              )}

              {warnings.length > 0 && (
                <IssueList title="Warnings" issues={warnings} tone="amber" />
              )}
            </>
          )}
        </div>

        <div
          style={{
            padding: '16px 20px',
            borderTop: '1px solid var(--border)',
            display: 'flex',
            justifyContent: 'space-between',
            gap: 12,
          }}
        >
          <button onClick={onClose} style={secondaryButtonStyle()}>
            Close
          </button>

          <button
            onClick={handleUseWorkbook}
            disabled={!validation?.valid}
            style={primaryButtonStyle(!validation?.valid)}
          >
            Use workbook
          </button>
        </div>
      </div>
    </div>
  )
}

function SummaryCard({ label, value, tone = 'neutral' }) {
  const palette = {
    neutral: {
      border: 'var(--border)',
      bg: 'var(--bg-base)',
      color: 'var(--text-primary)',
      sub: 'var(--text-muted)',
    },
    green: {
      border: 'rgba(34,197,94,0.18)',
      bg: 'rgba(34,197,94,0.08)',
      color: '#15803d',
      sub: '#166534',
    },
    red: {
      border: 'rgba(239,68,68,0.18)',
      bg: 'rgba(239,68,68,0.08)',
      color: '#dc2626',
      sub: '#991b1b',
    },
    amber: {
      border: 'rgba(245,158,11,0.18)',
      bg: 'rgba(245,158,11,0.08)',
      color: '#b45309',
      sub: '#92400e',
    },
  }

  const p = palette[tone]

  return (
    <div
      style={{
        border: `1px solid ${p.border}`,
        background: p.bg,
        borderRadius: 14,
        padding: 14,
      }}
    >
      <div style={{ fontSize: 12, color: p.sub }}>{label}</div>
      <div style={{ fontSize: 18, fontWeight: 800, color: p.color, marginTop: 4 }}>
        {value}
      </div>
    </div>
  )
}

function IssueList({ title, issues, tone = 'red' }) {
  const palette = {
    red: {
      border: 'rgba(239,68,68,0.18)',
      bg: 'rgba(239,68,68,0.08)',
      color: '#dc2626',
    },
    amber: {
      border: 'rgba(245,158,11,0.18)',
      bg: 'rgba(245,158,11,0.08)',
      color: '#b45309',
    },
  }

  const p = palette[tone]

  return (
    <div
      style={{
        border: `1px solid ${p.border}`,
        background: p.bg,
        borderRadius: 14,
        padding: 14,
      }}
    >
      <div
        style={{
          fontSize: 14,
          fontWeight: 800,
          color: p.color,
          display: 'flex',
          alignItems: 'center',
          gap: 8,
          marginBottom: 10,
        }}
      >
        <AlertTriangle size={15} />
        {title}
      </div>

      <div style={{ display: 'flex', flexDirection: 'column', gap: 10 }}>
        {issues.slice(0, 25).map((issue, index) => (
          <div
            key={index}
            style={{
              background: 'rgba(255,255,255,0.55)',
              borderRadius: 10,
              padding: 10,
              fontSize: 13,
              color: 'var(--text-primary)',
            }}
          >
            <div style={{ fontWeight: 700 }}>
              {issue.sheet}
              {issue.row ? ` · Row ${issue.row}` : ''}
              {issue.column ? ` · ${issue.column}` : ''}
            </div>
            <div style={{ marginTop: 4, color: 'var(--text-secondary)' }}>
              {issue.message}
            </div>
          </div>
        ))}

        {issues.length > 25 && (
          <div style={{ fontSize: 12, color: 'var(--text-muted)' }}>
            +{issues.length - 25} more {title.toLowerCase()}
          </div>
        )}
      </div>
    </div>
  )
}

function primaryButtonStyle(disabled = false) {
  return {
    display: 'inline-flex',
    alignItems: 'center',
    gap: 8,
    justifyContent: 'center',
    padding: '10px 14px',
    borderRadius: 12,
    border: '1px solid rgba(59,130,246,0.22)',
    background: disabled ? 'rgba(59,130,246,0.35)' : '#3b82f6',
    color: '#fff',
    fontWeight: 700,
    cursor: disabled ? 'not-allowed' : 'pointer',
    minWidth: 150,
  }
}

function secondaryButtonStyle() {
  return {
    display: 'inline-flex',
    alignItems: 'center',
    gap: 8,
    justifyContent: 'center',
    padding: '10px 14px',
    borderRadius: 12,
    border: '1px solid var(--border)',
    background: 'var(--bg-base)',
    color: 'var(--text-secondary)',
    fontWeight: 700,
    cursor: 'pointer',
  }
}